# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.tabWidget = QtWidgets.QTabWidget(Widget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tabZ = QtWidgets.QWidget()
        self.tabZ.setObjectName("tabZ")
        self.graphicsViewZ = QtWidgets.QGraphicsView(self.tabZ)
        self.graphicsViewZ.setGeometry(QtCore.QRect(60, 90, 671, 471))
        self.graphicsViewZ.setObjectName("graphicsViewZ")
        self.pushButton = QtWidgets.QPushButton(self.tabZ)
        self.pushButton.setGeometry(QtCore.QRect(630, 30, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tabZ, "")
        self.tabAE = QtWidgets.QWidget()
        self.tabAE.setObjectName("tabAE")
        self.graphicsViewAE = QtWidgets.QGraphicsView(self.tabAE)
        self.graphicsViewAE.setGeometry(QtCore.QRect(60, 80, 671, 471))
        self.graphicsViewAE.setObjectName("graphicsViewAE")
        self.tabWidget.addTab(self.tabAE, "")
        self.tabLSTM = QtWidgets.QWidget()
        self.tabLSTM.setObjectName("tabLSTM")
        self.graphicsViewLSTM = QtWidgets.QGraphicsView(self.tabLSTM)
        self.graphicsViewLSTM.setGeometry(QtCore.QRect(60, 80, 671, 471))
        self.graphicsViewLSTM.setObjectName("graphicsViewLSTM")
        self.tabWidget.addTab(self.tabLSTM, "")

        self.retranslateUi(Widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton.setText(_translate("Widget", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabZ), _translate("Widget", "Z-score"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAE), _translate("Widget", "AE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLSTM), _translate("Widget", "LSTM"))
